### ISSUE TITLE
Parser error in chapter 4

### ISSUE THREAD

**Issue by leandernikolaus** [viperproject/program-proofs-gobra#9]
Hi, thanks for the great work!
I get a parser error on Chapter 4:
![image](https://github.com/viperproject/program-proofs-gobra/assets/7900693/2dfd4a6e-8592-4cd0-abaf-9b7d00336373)

I just installed the VSCode plugin. 
Can an outdated version cause this?

**Comment by jcp19** [comment]
Hi @leandernikolaus, thanks for reporting this! I guess that our plugin is using an outdated version of Gobra. Going into the Gobra IDE settings and changing the option `Build Version` to `Nightly` instead of the default `Stable` should fix the problem.

**Comment by leandernikolaus** [comment]
@jcp19 Thanks, that solved the error.
Keep up the great work!
